name: ConstruccionProyectos

# Cuando se hara?
on:
  push:
    branches:
      - main

# Permisos?
permissions:
  contents: write

# Que tiene que hacer?
jobs:
  crear-los-pdfs:
    runs-on: ubuntu-latest
 #   if: "contains(github.event.head_commit.message, '[build]')"

    steps:
    - uses: actions/checkout@v4

    - name: Instalamos las dependencias
      run: make dependences

    - name: SMX - Proyecto
      run: make proyecto-smx
    - name: SMX - Programaciones
      run: make programaciones-smx
      
    - name: DAW - Proyecto
      run: make proyecto-daw	
    - name: DAW - Programaciones
      run: make programaciones-daw

    - name: DAM - Proyecto
      run: make proyecto-dam	
    - name: DAM - Programaciones
      run: make programaciones-dam 
    
    - name: ASIR - Proyecto
      run: make proyecto-asir
    - name: ASIR - Programaciones
      run: make programaciones-asir
      
    - uses: actions/upload-artifact@v4
      with:
        name: PDFs-PCCFs
        path: PDFS/ 

